##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/libmatekbd
    - autoconf-archive
    - gcc
    - git
    - gobject-introspection
    - gtk3
    - intltool
    - libxklavier
    - make
    - mate-common
    - which

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/libmatekbd
    - git
    - gobject-introspection
    - intltool
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libxklavier-dev
    - make
    - mate-common

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/libmatekbd.git
    - desktop-file-utils
    - gcc
    - gcc-c++
    - git
    - gobject-introspection-devel
    - gsettings-desktop-schemas-devel
    - gtk3-devel
    - libICE-devel
    - libxklavier-devel
    - make
    - mate-common
    - redhat-rpm-config

  ubuntu:
    - git
    - gobject-introspection
    - intltool
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libxklavier-dev
    - make
    - mate-common

variables:
  - CFLAGS="-Wall -Werror=format-security"

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  -     bash ./debian.sh
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: libmatekbd-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release

